### ISSUE TITLE
Veri tipi sorunu

### ISSUE THREAD

**Issue by IsmailOzolmezoglu** [yunusemrecebe/ParaniYonet#1]
Bu hali ile kimsenin kullanmasını tavsiye etmem, para birimi için seçilen veri tipi yanlış 0.50 ya da 0,50 şeklinde para birimlerini üste yuvarlar ve yüksek miktarlarda ciddi sapmalar yaşarsınız.

**Comment by yunusemrecebe** [comment]
> Bu hali ile kimsenin kullanmasını tavsiye etmem, para birimi için seçilen veri tipi yanlış 0.50 ya da 0,50 şeklinde para birimlerini üste yuvarlar ve yüksek miktarlarda ciddi sapmalar yaşarsınız.

Geri bildiriminiz için teşekkürler. Problem giderilmiştir, bilginize.
